//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Adn_Id { get; set; }
        public string Adn_LoginName { get; set; }
        public string Adn_Pwd { get; set; }
        public string Adn_Type { get; set; }
        public string Adn_Name { get; set; }
        public string Adn_Tel { get; set; }
        public string Adn_Email { get; set; }
        public Nullable<System.DateTime> Adn_CreateDt { get; set; }
        public Nullable<System.DateTime> Adn_Udt { get; set; }
    }
}
