//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advisory
    {
        public int Adv_Id { get; set; }
        public Nullable<int> Adv_Ptt_Id { get; set; }
        public Nullable<decimal> Adv_Pirce { get; set; }
        public Nullable<decimal> Adv_SellPrice { get; set; }
        public Nullable<decimal> Adv_MemberPrice { get; set; }
    }
}
