//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int Ara_Id { get; set; }
        public string Ara_Name { get; set; }
        public Nullable<int> Ara_Aty_Id { get; set; }
        public Nullable<System.DateTime> Ara_CDt { get; set; }
        public string Ara_Desc { get; set; }
    }
}
