//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoXian
    {
        public int Bxn_Id { get; set; }
        public Nullable<int> Bxn_Ptt_Id { get; set; }
        public Nullable<int> Bxn_Type { get; set; }
        public Nullable<decimal> Bxn_Price { get; set; }
        public Nullable<decimal> Bxn_SellPrice { get; set; }
        public Nullable<decimal> Bxn_MemberPrice { get; set; }
        public Nullable<int> Bxn_DtType { get; set; }
    }
}
