//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Odr_Id { get; set; }
        public string Odr_Code { get; set; }
        public Nullable<decimal> Odr_Amount { get; set; }
        public Nullable<System.DateTime> Odr_Dt { get; set; }
        public string Odr_Remark { get; set; }
        public Nullable<int> Odr_Use_Id { get; set; }
        public Nullable<int> Odr_Ads_Id { get; set; }
        public string Odr_Status { get; set; }
        public Nullable<System.DateTime> Odr_Sdt { get; set; }
        public Nullable<System.DateTime> Odr_Edt { get; set; }
        public Nullable<int> Odr_Ara_Id { get; set; }
        public Nullable<int> Odr_Zqu_Id { get; set; }
        public string Odr_BxuIds { get; set; }
        public string Odr_Yjjs { get; set; }
    }
}
