//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Odd_Id { get; set; }
        public Nullable<int> Odd_Ara_Id { get; set; }
        public Nullable<int> Odd_Odr_Id { get; set; }
        public Nullable<int> Odd_Prd_Id { get; set; }
        public Nullable<int> Odd_Quantity { get; set; }
        public Nullable<int> Odd_Days { get; set; }
        public string Odd_Type { get; set; }
        public Nullable<System.DateTime> Odd_CreateDt { get; set; }
        public string Odd_Status { get; set; }
        public string Odd_KDNo { get; set; }
    }
}
