//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdType
    {
        public int Ptt_Id { get; set; }
        public string Ptt_Name { get; set; }
        public Nullable<int> Ptt_ParentId { get; set; }
        public string Ptt_Desc { get; set; }
        public Nullable<int> Ptt_Sort { get; set; }
        public Nullable<System.DateTime> Ptt_CreateDt { get; set; }
        public Nullable<System.DateTime> Ptt_UpdateDt { get; set; }
    }
}
