//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Pce_Id { get; set; }
        public Nullable<int> Pce_Prd_Id { get; set; }
        public Nullable<int> Pce_Sup_Id { get; set; }
        public Nullable<int> Pce_Aty_Id { get; set; }
        public Nullable<int> Pce_Ara_Id { get; set; }
        public Nullable<int> Pce_Dtt_Id { get; set; }
        public Nullable<decimal> Pce_Price { get; set; }
        public Nullable<decimal> Pce_SellPrice { get; set; }
        public Nullable<decimal> Pce_MemberPrice { get; set; }
        public Nullable<double> Pce_Dis { get; set; }
    }
}
