//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Mobel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Use_Id { get; set; }
        public string Use_LoginName { get; set; }
        public string Use_Pwd { get; set; }
        public string Use_Type { get; set; }
        public string Use_Mobile { get; set; }
        public string Use_Email { get; set; }
        public string Use_Code { get; set; }
        public Nullable<System.DateTime> Use_CreateDt { get; set; }
        public Nullable<System.DateTime> Use_UpdateDt { get; set; }
        public string Use_Name { get; set; }
        public string Use_HzCode { get; set; }
        public string Use_QdName { get; set; }
        public string Use_QdCode { get; set; }
        public string Use_Status { get; set; }
    }
}
